// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: upload/upload_service.proto

package upload

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateTranscodeStatusRequest carries transcode outcome details.
type UpdateTranscodeStatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VideoUuid         string                 `protobuf:"bytes,1,opt,name=video_uuid,json=videoUuid,proto3" json:"video_uuid,omitempty"`
	TranscodeTaskUuid string                 `protobuf:"bytes,2,opt,name=transcode_task_uuid,json=transcodeTaskUuid,proto3" json:"transcode_task_uuid,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	VideoUrl          string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateTranscodeStatusRequest) Reset() {
	*x = UpdateTranscodeStatusRequest{}
	mi := &file_upload_upload_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTranscodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTranscodeStatusRequest) ProtoMessage() {}

func (x *UpdateTranscodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upload_upload_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTranscodeStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTranscodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_upload_upload_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateTranscodeStatusRequest) GetVideoUuid() string {
	if x != nil {
		return x.VideoUuid
	}
	return ""
}

func (x *UpdateTranscodeStatusRequest) GetTranscodeTaskUuid() string {
	if x != nil {
		return x.TranscodeTaskUuid
	}
	return ""
}

func (x *UpdateTranscodeStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTranscodeStatusRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *UpdateTranscodeStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// UpdateTranscodeStatusResponse reports whether the update succeeded.
type UpdateTranscodeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTranscodeStatusResponse) Reset() {
	*x = UpdateTranscodeStatusResponse{}
	mi := &file_upload_upload_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTranscodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTranscodeStatusResponse) ProtoMessage() {}

func (x *UpdateTranscodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upload_upload_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTranscodeStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTranscodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_upload_upload_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateTranscodeStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTranscodeStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_upload_upload_service_proto protoreflect.FileDescriptor

const file_upload_upload_service_proto_rawDesc = "" +
	"\n" +
	"\x1bupload/upload_service.proto\x12\x06upload\"\xc7\x01\n" +
	"\x1cUpdateTranscodeStatusRequest\x12\x1d\n" +
	"\n" +
	"video_uuid\x18\x01 \x01(\tR\tvideoUuid\x12.\n" +
	"\x13transcode_task_uuid\x18\x02 \x01(\tR\x11transcodeTaskUuid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"S\n" +
	"\x1dUpdateTranscodeStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2u\n" +
	"\rUploadService\x12d\n" +
	"\x15UpdateTranscodeStatus\x12$.upload.UpdateTranscodeStatusRequest\x1a%.upload.UpdateTranscodeStatusResponseB\x1dZ\x1bupload-service/proto/uploadb\x06proto3"

var (
	file_upload_upload_service_proto_rawDescOnce sync.Once
	file_upload_upload_service_proto_rawDescData []byte
)

func file_upload_upload_service_proto_rawDescGZIP() []byte {
	file_upload_upload_service_proto_rawDescOnce.Do(func() {
		file_upload_upload_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upload_upload_service_proto_rawDesc), len(file_upload_upload_service_proto_rawDesc)))
	})
	return file_upload_upload_service_proto_rawDescData
}

var file_upload_upload_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_upload_upload_service_proto_goTypes = []any{
	(*UpdateTranscodeStatusRequest)(nil),  // 0: upload.UpdateTranscodeStatusRequest
	(*UpdateTranscodeStatusResponse)(nil), // 1: upload.UpdateTranscodeStatusResponse
}
var file_upload_upload_service_proto_depIdxs = []int32{
	0, // 0: upload.UploadService.UpdateTranscodeStatus:input_type -> upload.UpdateTranscodeStatusRequest
	1, // 1: upload.UploadService.UpdateTranscodeStatus:output_type -> upload.UpdateTranscodeStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_upload_upload_service_proto_init() }
func file_upload_upload_service_proto_init() {
	if File_upload_upload_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upload_upload_service_proto_rawDesc), len(file_upload_upload_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_upload_upload_service_proto_goTypes,
		DependencyIndexes: file_upload_upload_service_proto_depIdxs,
		MessageInfos:      file_upload_upload_service_proto_msgTypes,
	}.Build()
	File_upload_upload_service_proto = out.File
	file_upload_upload_service_proto_goTypes = nil
	file_upload_upload_service_proto_depIdxs = nil
}
